export default Data = [
  { id: 1, text: "Item One", color: "red", text2: "aaaaa", text3: "bbbbbb" },
  { id: 2, text: "Item Two", color: "blue", text2: "aaaaa", text3: "bbbbbb" },
  {
    id: 3,
    text: "Item Three",
    color: "yellow",
    text2: "aaaaa",
    text3: "bbbbbb",
  },
  { id: 4, text: "Item Four", color: "green", text2: "aaaaa", text3: "bbbbbb" },
  {
    id: 5,
    text: "Item Five",
    color: "orange",
    text2: "aaaaa",
    text3: "bbbbbb",
  },
  { id: 6, text: "Item Six", color: "red", text2: "aaaaa", text3: "bbbbbb" },
  { id: 7, text: "Item Seven", color: "blue", text2: "aaaaa", text3: "bbbbbb" },
  {
    id: 8,
    text: "Item Eight",
    color: "yellow",
    text2: "aaaaa",
    text3: "bbbbbb",
  },
  { id: 9, text: "Item Nine", color: "green", text2: "aaaaa", text3: "bbbbbb" },
  {
    id: 10,
    text: "Item Ten",
    color: "orange",
    text2: "aaaaa",
    text3: "bbbbbb",
  },
  {
    id: 11,
    text: "Item Eleven",
    color: "red",
    text2: "aaaaa",
    text3: "bbbbbb",
  },
  {
    id: 12,
    text: "Item Twelve",
    color: "blue",
    text2: "aaaaa",
    text3: "bbbbbb",
  },
  {
    id: 13,
    text: "Item Thirteen",
    color: "yellow",
    text2: "aaaaa",
    text3: "bbbbbb",
  },
  {
    id: 14,
    text: "Item Fourteen",
    color: "green",
    text2: "aaaaa",
    text3: "bbbbbb",
  },
  {
    id: 15,
    text: "Item Fifteen",
    color: "orange",
    text2: "aaaaa",
    text3: "bbbbbb",
  },
];
